CREATE SCHEMA "FINALPROJECT"."DWH";

CREATE TABLE "FINALPROJECT"."DWH"."DIM_TEMPERATURE" LIKE "FINALPROJECT"."ODS"."TEMPERATURE";

insert into "DWH"."DIM_TEMPERATURE" select distinct * from "ODS"."TEMPERATURE";

CREATE TABLE "FINALPROJECT"."DWH"."DIM_PRECIPITATION" LIKE "FINALPROJECT"."ODS"."PRECIPITATION";

insert into "DWH"."DIM_PRECIPITATION" select distinct * from "ODS"."PRECIPITATION";

CREATE TABLE "FINALPROJECT"."DWH"."DIM_YELP_BUSINESS" LIKE "FINALPROJECT"."ODS"."YELP_BUSINESS";

insert into "DWH"."DIM_YELP_BUSINESS" select distinct * from "ODS"."YELP_BUSINESS";


CREATE TABLE "FINALPROJECT"."DWH"."DIM_YELP_USER" LIKE "FINALPROJECT"."ODS"."YELP_USER";

insert into "DWH"."DIM_YELP_USER" select distinct * from "ODS"."YELP_USER";


CREATE TABLE "FINALPROJECT"."DWH"."FACT_YELP_REVIEW" LIKE "FINALPROJECT"."ODS"."YELP_REVIEW";

insert into "DWH"."FACT_YELP_REVIEW" select r.* from "ODS"."YELP_REVIEW" r 
           JOIN "DWH"."DIM_YELP_BUSINESS" b ON r.business_id=b.business_id
           JOIN "DWH"."DIM_YELP_USER" u ON r.user_id=u.user_id
           JOIN "DWH"."DIM_TEMPERATURE" t on t.date=r.review_date
           JOIN "DWH"."DIM_PRECIPITATION" p on p.date=r.review_date;
